import random
import turtle
randomValue = 0
print('"?" to help\n')
pen = turtle.Pen()
while True:
    inputValue = str(input())
    if inputValue == "?":
        print('Enter a number to start')
        print('Enter "colorsOn" to make numbers colorful')
        print('Enter "colorsOff" to make numbers black')
        print('"><" to stop\n')
    if inputValue == "><":
        break
    if inputValue == "colorsOn":
        randomValue = 1
    if inputValue == "colorsOff":
        randomValue = 0
    length = len(inputValue)
    id = 0
    pen.reset()
    while id != length:
        symbol = inputValue[id]
        x = random.random()
        y = random.random()
        z = random.random()
        if symbol == "1":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.right(90)
            pen.forward(14)
            pen.left(90)
            pen.left(90)
            pen.down()
            pen.forward(14)
            pen.right(90)
            pen.up()
            pen.forward(7)
        elif symbol == "2":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.down()
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.up()
            pen.left(90)
            pen.forward(14)
            pen.right(90)
            pen.forward(7)
        elif symbol == "3":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.down()
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.backward(7)
            pen.left(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.up()
            pen.backward(7)
            pen.right(90)
            pen.forward(14)
            pen.right(90)
            pen.forward(7)
        elif symbol == "4":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.down()
            pen.right(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.backward(14)
            pen.up()
            pen.forward(14)
            pen.right(90)
            pen.forward(7)
        elif symbol == "5":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.right(90)
            pen.forward(14)
            pen.left(90)
            pen.down()
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.up()
            pen.forward(7)
        elif symbol == "6":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.right(90)
            pen.forward(7)
            pen.down()
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.up()
            pen.forward(7)
        elif symbol == "7":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.down()
            pen.forward(7)
            pen.right(90)
            pen.forward(14)
            pen.up()
            pen.backward(14)
            pen.left(90)
            pen.forward(7)
        elif symbol == "8":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.right(90)
            pen.forward(7)
            pen.down()
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.up()
            pen.backward(7)
            pen.left(90)
            pen.forward(7)
        elif symbol == "9":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.up()
            pen.right(90)
            pen.forward(14)
            pen.left(90)
            pen.down()
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.right(90)
            pen.forward(7)
            pen.up()
            pen.backward(7)
            pen.left(90)
            pen.forward(7)
        elif symbol == "0":
            if randomValue == 1:
                pen.color(x,y,z)
            pen.down()
            pen.right(90)
            pen.forward(14)
            pen.left(90)
            pen.forward(7)
            pen.left(90)
            pen.forward(14)
            pen.left(90)
            pen.forward(7)
            pen.up()
            pen.backward(14)
            pen.right(180)
        id += 1
    if id == length:
        pen.forward(7)
    
