import turtle
print('"?" to help\n')
t = turtle.Pen()
while True:
    a = str(input())
    if a == "?":
        print('Enter a number to start')
        print('"><" to stop\n')
    if a == "><":
        break
    b = len(a)
    id = 0
    t.reset()
    while id != b:
        j = a[id]
        if j == "1":
            t.right(90)
            t.forward(14)
            t.left(90)
            t.left(90)
            t.down()
            t.forward(14)
            t.right(90)
            t.up()
            t.forward(7)
        elif j == "2":
            t.down()
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.up()
            t.left(90)
            t.forward(14)
            t.right(90)
            t.forward(7)
        elif j == "3":
            t.down()
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.backward(7)
            t.left(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.up()
            t.backward(7)
            t.right(90)
            t.forward(14)
            t.right(90)
            t.forward(7)
        elif j == "4":
            t.down()
            t.right(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.backward(14)
            t.up()
            t.forward(14)
            t.right(90)
            t.forward(7)
        elif j == "5":
            t.right(90)
            t.forward(14)
            t.left(90)
            t.down()
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.up()
            t.forward(7)
        elif j == "6":
            t.right(90)
            t.forward(7)
            t.down()
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.up()
            t.forward(7)
        elif j == "7":
            t.down()
            t.forward(7)
            t.right(90)
            t.forward(14)
            t.up()
            t.backward(14)
            t.left(90)
            t.forward(7)
        elif j == "8":
            t.right(90)
            t.forward(7)
            t.down()
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.up()
            t.backward(7)
            t.left(90)
            t.forward(7)
        elif j == "9":
            t.up()
            t.right(90)
            t.forward(14)
            t.left(90)
            t.down()
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.right(90)
            t.forward(7)
            t.up()
            t.backward(7)
            t.left(90)
            t.forward(7)
        elif j == "0":
            t.down()
            t.right(90)
            t.forward(14)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(14)
            t.left(90)
            t.forward(7)
            t.up()
            t.backward(14)
            t.right(180)
        id += 1
    if id == b:
        t.forward(7)
    
